"""Initial commit

Revision ID: 0e94bfac3ffd
Revises: 
Create Date: 2023-09-27 19:42:15.581625

"""
import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import mysql
from sqlalchemy import String, Integer
from sqlalchemy.sql import table, column

# revision identifiers, used by Alembic.
revision = '0e94bfac3ffd'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('country',
    sa.Column('cnty_cod', sa.Unicode(length=3), nullable=False),
    sa.Column('cnty_name', sa.Unicode(length=120), nullable=True),
    sa.Column('cnty_iso', sa.Unicode(length=3), nullable=True),
    sa.Column('cnty_extension', sa.Unicode(length=10), nullable=True),
    sa.PrimaryKeyConstraint('cnty_cod', name=op.f('pk_country'))
    )
    op.create_table('role',
    sa.Column('role_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('role_name', sa.Unicode(length=120), nullable=True),
    sa.PrimaryKeyConstraint('role_id', name=op.f('pk_role'))
    )
    op.create_table('status',
    sa.Column('status_id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('status_name', sa.Unicode(length=120), nullable=True),
    sa.PrimaryKeyConstraint('status_id', name=op.f('pk_status'))
    )
    op.create_table('user',
    sa.Column('user_id', sa.Unicode(length=120), nullable=False),
    sa.Column('user_name', sa.Unicode(length=120), nullable=True),
    sa.Column('user_email', sa.Unicode(length=120), nullable=True),
    sa.Column('user_password', mysql.MEDIUMTEXT(collation='utf8mb4_unicode_ci'), nullable=True),
    sa.Column('user_about', sa.UnicodeText(), nullable=True),
    sa.Column('user_cdate', sa.DateTime(), nullable=True),
    sa.Column('user_llogin', sa.DateTime(), nullable=True),
    sa.Column('user_cnty', sa.Unicode(length=3), nullable=True),
    sa.Column('user_organization', sa.Unicode(length=120), nullable=True),
    sa.Column('user_active', sa.Integer(), nullable=True),
    sa.Column('user_role', sa.Integer(), nullable=True),
    sa.Column('user_apikey', sa.Unicode(length=64), nullable=True),
    sa.Column('user_password_reset_key', sa.Unicode(length=64), nullable=True),
    sa.Column('user_password_reset_token', sa.Unicode(length=64), nullable=True),
    sa.Column('user_password_reset_expires_on', sa.DateTime(), nullable=True),
    sa.Column('tags', sa.UnicodeText(), nullable=True),
    sa.Column('extras', sa.UnicodeText(), nullable=True),
    sa.ForeignKeyConstraint(['user_active'], ['status.status_id'], name=op.f('fk_user_user_active_status')),
    sa.ForeignKeyConstraint(['user_cnty'], ['country.cnty_cod'], name=op.f('fk_user_user_cnty_country')),
    sa.ForeignKeyConstraint(['user_role'], ['role.role_id'], name=op.f('fk_user_user_role_role')),
    sa.PrimaryKeyConstraint('user_id', name=op.f('pk_user'))
    )

    countries = [
	{
		"cnty_cod" : "AD",
		"cnty_name" : "Andorra",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AE",
		"cnty_name" : "United Arab Emirates",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AF",
		"cnty_name" : "Afghanistan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AG",
		"cnty_name" : "Antigua and Barbuda",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AI",
		"cnty_name" : "Anguilla",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AL",
		"cnty_name" : "Albania",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AM",
		"cnty_name" : "Armenia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AO",
		"cnty_name" : "Angola",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AQ",
		"cnty_name" : "Antarctica",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AR",
		"cnty_name" : "Argentina",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AS",
		"cnty_name" : "American Samoa",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AT",
		"cnty_name" : "Austria",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AU",
		"cnty_name" : "Australia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AW",
		"cnty_name" : "Aruba",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AX",
		"cnty_name" : "Åland Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "AZ",
		"cnty_name" : "Azerbaijan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BA",
		"cnty_name" : "Bosnia and Herzegovina",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BB",
		"cnty_name" : "Barbados",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BD",
		"cnty_name" : "Bangladesh",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BE",
		"cnty_name" : "Belgium",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BF",
		"cnty_name" : "Burkina Faso",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BG",
		"cnty_name" : "Bulgaria",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BH",
		"cnty_name" : "Bahrain",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BI",
		"cnty_name" : "Burundi",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BJ",
		"cnty_name" : "Benin",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BL",
		"cnty_name" : "Saint Barthélemy",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BM",
		"cnty_name" : "Bermuda",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BN",
		"cnty_name" : "Brunei Darussalam",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BO",
		"cnty_name" : "Bolivia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BQ",
		"cnty_name" : "Caribbean Netherlands ",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BR",
		"cnty_name" : "Brazil",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BS",
		"cnty_name" : "Bahamas",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BT",
		"cnty_name" : "Bhutan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BV",
		"cnty_name" : "Bouvet Island",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BW",
		"cnty_name" : "Botswana",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BY",
		"cnty_name" : "Belarus",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "BZ",
		"cnty_name" : "Belize",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CA",
		"cnty_name" : "Canada",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CC",
		"cnty_name" : "Cocos (Keeling) Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CD",
		"cnty_name" : "Congo, Democratic Republic of",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CF",
		"cnty_name" : "Central African Republic",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CG",
		"cnty_name" : "Congo",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CH",
		"cnty_name" : "Switzerland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CI",
		"cnty_name" : "Côte d'Ivoire",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CK",
		"cnty_name" : "Cook Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CL",
		"cnty_name" : "Chile",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CM",
		"cnty_name" : "Cameroon",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CN",
		"cnty_name" : "China",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CO",
		"cnty_name" : "Colombia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CR",
		"cnty_name" : "Costa Rica",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CU",
		"cnty_name" : "Cuba",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CV",
		"cnty_name" : "Cape Verde",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CW",
		"cnty_name" : "Curaçao",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CX",
		"cnty_name" : "Christmas Island",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CY",
		"cnty_name" : "Cyprus",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "CZ",
		"cnty_name" : "Czech Republic",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DE",
		"cnty_name" : "Germany",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DJ",
		"cnty_name" : "Djibouti",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DK",
		"cnty_name" : "Denmark",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DM",
		"cnty_name" : "Dominica",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DO",
		"cnty_name" : "Dominican Republic",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "DZ",
		"cnty_name" : "Algeria",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "EC",
		"cnty_name" : "Ecuador",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "EE",
		"cnty_name" : "Estonia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "EG",
		"cnty_name" : "Egypt",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "EH",
		"cnty_name" : "Western Sahara",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ER",
		"cnty_name" : "Eritrea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ES",
		"cnty_name" : "Spain",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ET",
		"cnty_name" : "Ethiopia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FI",
		"cnty_name" : "Finland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FJ",
		"cnty_name" : "Fiji",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FK",
		"cnty_name" : "Falkland Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FM",
		"cnty_name" : "Micronesia, Federated States of",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FO",
		"cnty_name" : "Faroe Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "FR",
		"cnty_name" : "France",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GA",
		"cnty_name" : "Gabon",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GB",
		"cnty_name" : "United Kingdom",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GD",
		"cnty_name" : "Grenada",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GE",
		"cnty_name" : "Georgia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GF",
		"cnty_name" : "French Guiana",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GG",
		"cnty_name" : "Guernsey",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GH",
		"cnty_name" : "Ghana",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GI",
		"cnty_name" : "Gibraltar",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GL",
		"cnty_name" : "Greenland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GM",
		"cnty_name" : "Gambia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GN",
		"cnty_name" : "Guinea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GP",
		"cnty_name" : "Guadeloupe",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GQ",
		"cnty_name" : "Equatorial Guinea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GR",
		"cnty_name" : "Greece",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GS",
		"cnty_name" : "South Georgia and the South Sandwich Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GT",
		"cnty_name" : "Guatemala",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GU",
		"cnty_name" : "Guam",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GW",
		"cnty_name" : "Guinea-Bissau",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "GY",
		"cnty_name" : "Guyana",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HK",
		"cnty_name" : "Hong Kong",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HM",
		"cnty_name" : "Heard and McDonald Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HN",
		"cnty_name" : "Honduras",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HR",
		"cnty_name" : "Croatia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HT",
		"cnty_name" : "Haiti",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "HU",
		"cnty_name" : "Hungary",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ID",
		"cnty_name" : "Indonesia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IE",
		"cnty_name" : "Ireland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IL",
		"cnty_name" : "Israel",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IM",
		"cnty_name" : "Isle of Man",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IN",
		"cnty_name" : "India",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IO",
		"cnty_name" : "British Indian Ocean Territory",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IQ",
		"cnty_name" : "Iraq",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IR",
		"cnty_name" : "Iran",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IS",
		"cnty_name" : "Iceland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "IT",
		"cnty_name" : "Italy",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "JE",
		"cnty_name" : "Jersey",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "JM",
		"cnty_name" : "Jamaica",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "JO",
		"cnty_name" : "Jordan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "JP",
		"cnty_name" : "Japan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KE",
		"cnty_name" : "Kenya",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KG",
		"cnty_name" : "Kyrgyzstan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KH",
		"cnty_name" : "Cambodia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KI",
		"cnty_name" : "Kiribati",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KM",
		"cnty_name" : "Comoros",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KN",
		"cnty_name" : "Saint Kitts and Nevis",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KP",
		"cnty_name" : "North Korea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KR",
		"cnty_name" : "South Korea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KW",
		"cnty_name" : "Kuwait",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KY",
		"cnty_name" : "Cayman Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "KZ",
		"cnty_name" : "Kazakhstan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LA",
		"cnty_name" : "Lao People's Democratic Republic",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LB",
		"cnty_name" : "Lebanon",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LC",
		"cnty_name" : "Saint Lucia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LI",
		"cnty_name" : "Liechtenstein",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LK",
		"cnty_name" : "Sri Lanka",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LR",
		"cnty_name" : "Liberia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LS",
		"cnty_name" : "Lesotho",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LT",
		"cnty_name" : "Lithuania",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LU",
		"cnty_name" : "Luxembourg",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LV",
		"cnty_name" : "Latvia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "LY",
		"cnty_name" : "Libya",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MA",
		"cnty_name" : "Morocco",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MC",
		"cnty_name" : "Monaco",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MD",
		"cnty_name" : "Moldova",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ME",
		"cnty_name" : "Montenegro",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MF",
		"cnty_name" : "Saint-Martin (France)",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MG",
		"cnty_name" : "Madagascar",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MH",
		"cnty_name" : "Marshall Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MK",
		"cnty_name" : "Macedonia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ML",
		"cnty_name" : "Mali",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MM",
		"cnty_name" : "Myanmar",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MN",
		"cnty_name" : "Mongolia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MO",
		"cnty_name" : "Macau",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MP",
		"cnty_name" : "Northern Mariana Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MQ",
		"cnty_name" : "Martinique",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MR",
		"cnty_name" : "Mauritania",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MS",
		"cnty_name" : "Montserrat",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MT",
		"cnty_name" : "Malta",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MU",
		"cnty_name" : "Mauritius",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MV",
		"cnty_name" : "Maldives",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MW",
		"cnty_name" : "Malawi",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MX",
		"cnty_name" : "Mexico",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MY",
		"cnty_name" : "Malaysia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "MZ",
		"cnty_name" : "Mozambique",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NA",
		"cnty_name" : "Namibia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NC",
		"cnty_name" : "New Caledonia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NE",
		"cnty_name" : "Niger",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NF",
		"cnty_name" : "Norfolk Island",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NG",
		"cnty_name" : "Nigeria",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NI",
		"cnty_name" : "Nicaragua",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NL",
		"cnty_name" : "The Netherlands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NO",
		"cnty_name" : "Norway",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NP",
		"cnty_name" : "Nepal",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NR",
		"cnty_name" : "Nauru",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NU",
		"cnty_name" : "Niue",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "NZ",
		"cnty_name" : "New Zealand",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "OM",
		"cnty_name" : "Oman",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PA",
		"cnty_name" : "Panama",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PE",
		"cnty_name" : "Peru",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PF",
		"cnty_name" : "French Polynesia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PG",
		"cnty_name" : "Papua New Guinea",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PH",
		"cnty_name" : "Philippines",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PK",
		"cnty_name" : "Pakistan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PL",
		"cnty_name" : "Poland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PM",
		"cnty_name" : "St. Pierre and Miquelon",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PN",
		"cnty_name" : "Pitcairn",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PR",
		"cnty_name" : "Puerto Rico",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PS",
		"cnty_name" : "Palestine, State of",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PT",
		"cnty_name" : "Portugal",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PW",
		"cnty_name" : "Palau",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "PY",
		"cnty_name" : "Paraguay",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "QA",
		"cnty_name" : "Qatar",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "RE",
		"cnty_name" : "Réunion",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "RO",
		"cnty_name" : "Romania",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "RS",
		"cnty_name" : "Serbia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "RU",
		"cnty_name" : "Russian Federation",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "RW",
		"cnty_name" : "Rwanda",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SA",
		"cnty_name" : "Saudi Arabia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SB",
		"cnty_name" : "Solomon Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SC",
		"cnty_name" : "Seychelles",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SD",
		"cnty_name" : "Sudan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SE",
		"cnty_name" : "Sweden",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SG",
		"cnty_name" : "Singapore",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SH",
		"cnty_name" : "Saint Helena",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SI",
		"cnty_name" : "Slovenia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SJ",
		"cnty_name" : "Svalbard and Jan Mayen Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SK",
		"cnty_name" : "Slovakia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SL",
		"cnty_name" : "Sierra Leone",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SM",
		"cnty_name" : "San Marino",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SN",
		"cnty_name" : "Senegal",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SO",
		"cnty_name" : "Somalia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SR",
		"cnty_name" : "Suriname",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SS",
		"cnty_name" : "South Sudan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ST",
		"cnty_name" : "Sao Tome and Principe",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SV",
		"cnty_name" : "El Salvador",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SX",
		"cnty_name" : "Sint Maarten (Dutch part)",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SY",
		"cnty_name" : "Syria",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "SZ",
		"cnty_name" : "Swaziland",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TC",
		"cnty_name" : "Turks and Caicos Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TD",
		"cnty_name" : "Chad",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TF",
		"cnty_name" : "French Southern Territories",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TG",
		"cnty_name" : "Togo",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TH",
		"cnty_name" : "Thailand",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TJ",
		"cnty_name" : "Tajikistan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TK",
		"cnty_name" : "Tokelau",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TL",
		"cnty_name" : "Timor-Leste",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TM",
		"cnty_name" : "Turkmenistan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TN",
		"cnty_name" : "Tunisia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TO",
		"cnty_name" : "Tonga",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TR",
		"cnty_name" : "Turkey",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TT",
		"cnty_name" : "Trinidad and Tobago",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TV",
		"cnty_name" : "Tuvalu",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TW",
		"cnty_name" : "Taiwan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "TZ",
		"cnty_name" : "Tanzania",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "UA",
		"cnty_name" : "Ukraine",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "UG",
		"cnty_name" : "Uganda",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "UM",
		"cnty_name" : "United States Minor Outlying Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "US",
		"cnty_name" : "United States",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "UY",
		"cnty_name" : "Uruguay",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "UZ",
		"cnty_name" : "Uzbekistan",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VA",
		"cnty_name" : "Vatican",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VC",
		"cnty_name" : "Saint Vincent and the Grenadines",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VE",
		"cnty_name" : "Venezuela",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VG",
		"cnty_name" : "Virgin Islands (British)",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VI",
		"cnty_name" : "Virgin Islands (U.S.)",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VN",
		"cnty_name" : "Vietnam",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "VU",
		"cnty_name" : "Vanuatu",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "WF",
		"cnty_name" : "Wallis and Futuna Islands",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "WS",
		"cnty_name" : "Samoa",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "YE",
		"cnty_name" : "Yemen",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "YT",
		"cnty_name" : "Mayotte",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ZA",
		"cnty_name" : "South Africa",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ZM",
		"cnty_name" : "Zambia",
		"cnty_iso" : None
	},
	{
		"cnty_cod" : "ZW",
		"cnty_name" : "Zimbabwe",
		"cnty_iso" : None
	}
]


    table_country = table(
        "country",
        column("cnty_cod", String),
        column("cnty_name", String),
    )
    try:
        op.bulk_insert(table_country, countries)
    except Exception as e:
        print(str(e))
        pass

    roles = [
        {
            "role_id": 1,
            "role_name": "Normal",
        },
        {
            "role_id": 2,
            "role_name": "Administrator",
        },
    ]

    table_role = table(
        "role",
        column("role_id", Integer),
        column("role_name", String),
    )
    try:
        op.bulk_insert(table_role, roles)
    except Exception as e:
        print(str(e))
        pass

    status = [
        {
            "status_id": 2,
            "status_name": "Inactive",
        },
        {
            "status_id": 1,
            "status_name": "Active",
        },

    ]

    table_status = table(
        "status",
        column("status_id", Integer),
        column("status_name", String),
    )
    try:
        op.bulk_insert(table_status, status)
    except Exception as e:
        print(str(e))
        pass

    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    op.drop_table('status')
    op.drop_table('role')
    op.drop_table('country')
    # ### end Alembic commands ###
